# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

language: python
python:
    - "2.7"
services: docker

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

install:
jobs:
  include:
  - name: Test platformio
    install:
    - pip install -U platformio

    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/31/Adafruit Unified Sensor
    # http://platformio.org/lib/show/44/Time

    - platformio lib -g install 19 44
    env:
    - PLATFORMIO_CI_SRC=arduino_sketch/arduino_sketch.ino
    script:
    - platformio ci --project-conf=platformio.ini
  - name: Validate wiki markdown
    install:
    - docker build -t wiki-validator -f test/Dockerfile
    script:
    - docker run wiki-validator
    # This shouldn't fail PRs, so once we're happy with the method we can gate it like this:
    # - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker run wiki-validator; fi'
    


